# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmaexamen',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmaexamen',
            name='id_alarmaexamen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id_examen',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id_tarea',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='repeticionexamen',
            name='horaexamen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
