# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_auto_20161021_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='id_tarea',
        ),
    ]
