# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examen', '0003_remove_examen_id_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
