# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_examen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmaexamen',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='repeticionexamen',
            name='horaexamen',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
