# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datoshorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='datosmateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=60)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='usuario.datoshorario')),
            ],
        ),
        migrations.CreateModel(
            name='datosusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('no_boleta', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('fecha', models.DateTimeField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.datosmateria')),
            ],
        ),
    ]
