# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_datosusuario_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
