# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_datosusuario_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='qr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
