# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmatarea',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmatarea',
            name='id_alarmatarea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repeticionalarma',
            name='horaalarma',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
