# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_datosusuario_carrera'),
        ('tarea', '0003_auto_20161030_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.datosusuario'),
        ),
    ]
