# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_auto_20161031_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmatarea',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repeticiontarea',
            name='horaalarma',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateField(),
        ),
    ]
