# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='id_semestre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='id_vacaciones',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
