# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semestre', '0002_auto_20161021_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
