# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosmateria',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
