# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_datosmateria_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horas',
            name='hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
