# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0003_auto_20161021_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='fecha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='horas',
            name='hora',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
