# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_auto_20161021_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='fin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
