# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_horas_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoshorario',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='semestre.semestre'),
        ),
        migrations.AlterField(
            model_name='datosmateria',
            name='grupo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='datosmateria',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='materia.datoshorario'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='materia.datosmateria'),
        ),
    ]
