# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0006_auto_20161031_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora', models.TimeField(blank=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.datosmateria')),
            ],
        ),
    ]
