# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0007_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semana',
            name='hora',
        ),
        migrations.AddField(
            model_name='semana',
            name='horaf',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='semana',
            name='horai',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
